### ISSUE TITLE
Poor running results I’ve got

### ISSUE THREAD

**Issue by swbyy** [taoqi98/FedNewsRec#9]
I have been able to run the code successfully and set the parameters according to the paper. I've got 70+ output in an experiment but the results are not as good as in the paper, the results are mostly around [0.5030970471878436, 0.21842349985408516, 0.22200034188572945, 0.2848765577690094].Is this because the model has not yet converged? Or after about how many outputs will the model converge?

**Comment by taoqi98** [comment]
I have checked my codes again. I found that the 4-th parameter passed to the function "fed_single_update'' should be the parameter "lambd'' instead of the parameter "lr'' . The parameter "lambd'' controls the intensity of the LDP noise, and this mistake will perturb the local model prediction with strong noise, which seriously hurt the model performance. In fact, the model can converge to 65 AUC after around 1000 rounds. I have fixed this issue.
